## 🧭 Overview — Creating NumPy Arrays (Explained Like You’re 10)

NumPy is like a **math helper robot** for Python.  
It’s really good at working with lots of numbers at once — faster than normal Python lists.

A **NumPy array** is like a **box grid** that holds numbers.  
- If the grid is one line → it’s called a **vector** (1-D array).  
- If the grid has rows and columns → it’s a **matrix** (2-D array).  

We can create arrays in different ways:
1. From **Python lists** (we tell NumPy to turn our list into an array).  
2. By **generating numbers automatically** (like counting, all zeros, or random numbers).  
3. By **making patterns** (like evenly spaced numbers).

Let’s look at each one with examples you can understand easily.  


In [2]:
# Step 1:
# import relevant libraries
import numpy as np

In [3]:
# Step 2: Create an empty array (like an empty box ready for numbers) & save in a variable
array0 = np.array([])
print("Empty array:", array0)


Empty array: []


In [5]:
# create an empty numpy array & save in a variable
array0 = np.array([]).tolist()  # use .tolist() to convert the NumPy array to a Python list 
array0

[]

In [45]:
# Step 3: Initialize a Python list & save in a variable
# Imagine you have 5 candies labeled 1–5. We store them in a list
list1 = [1, 2, 3, 4, 5]

# Now tell NumPy to make it an array (NumPy's own type of list)
array1 = np.array(list1)
print("One-dimensional array:", array1)  # one-dimensional arrays are vectors


One-dimensional array: [1 2 3 4 5]


In [21]:
# initialize a Python list & save in a variable
list1 = [1, 2, 3, 4, 5]

In [22]:
# create a one-dimensional numpy array from list1 & save in a variable
array1 = np.array(list1)
array1


array([1, 2, 3, 4, 5])

In [47]:
# Step 4: Initialize a nested Python list & save in a variable
# This is like stacking rows on top of each other — a little table
list2 = [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]] 

# # Now tell NumPy to make it an array (NumPy's own type of list). 
array2 = np.array(list2)
print("Two-dimensional array:\n", array2)  # two-dimensional arrays are matrices with 3 rows and 3 columns


Two-dimensional array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
# initialize list2 as a nested Python list
list2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [52]:
array3 = np.array([[1,2,3],[4,5,6]])
print(array3.shape)  # output (2, 3), meaning two rows, three columns


(2, 3)


In [28]:
# create a two-dimensional numpy array from list2 
array2 = np.array(list2)
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
# Step 5: Use np.arange() to create a list of numbers
# np.arange(start, stop, step)
# start = where to begin
# stop = where to end (it stops *before* this number)
# step = how much to count by
print("Array from 0 to 4:", np.arange(5))           # [0 1 2 3 4]
print("Even numbers 0–10:", np.arange(0, 11, 2))    # [0 2 4 6 8 10]


Array from 0 to 4: [0 1 2 3 4]
Even numbers 0–10: [ 0  2  4  6  8 10]


In [30]:
# create a numpy array containing integers 0 to 4 including 0 and 4
np.arange(5)

array([0, 1, 2, 3, 4])

In [31]:
# create a numpy array containing all even integers between 0 and 10 including 0 and 10
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [49]:
# Step 6: Make arrays full of zeros or ones
# np.zeros() and np.ones() are like “fill my box with zeros” or “fill my box with ones.”

print("Five zeros:", np.zeros(5))  # one-dimensional numpy array
print("4x5 grid of zeros:\n", np.zeros((4, 5)))  # two-dimensional numpy array

print("Six ones:", np.ones(6))  # one-dimensional numpy array
print("4x6 grid of ones:\n", np.ones((4, 6)))  # two-dimensional numpy array


Five zeros: [0. 0. 0. 0. 0.]
4x5 grid of zeros:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Six ones: [1. 1. 1. 1. 1. 1.]
4x6 grid of ones:
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [33]:
# create a one-dimenstional numpy array containing 5 zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [34]:
# create a two-dimensional numpy array of zeros having 4 rows and 5 columns
np.zeros((4, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [35]:
# create a one-dimenstional numpy array containing 6 ones
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [36]:
# create a two-dimensional numpy array of ones having 4 rows and 6 columns
np.ones((4, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [39]:
# Step 7: Create evenly spaced numbers from 1 to 2, including 1 and 2, using np.linspace()
# np.linspace(start, stop, num)
# It divides the space between start and stop into equal parts.
print("Nine numbers from 1 to 2:", np.linspace(1, 2, 9))


Nine numbers from 1 to 2: [1.    1.125 1.25  1.375 1.5   1.625 1.75  1.875 2.   ]


In [40]:
# create a numpy array of 9 evenly spaced numbers from 1 to 2, including 1 and 2
np.linspace(1, 2, 9)

array([1.   , 1.125, 1.25 , 1.375, 1.5  , 1.625, 1.75 , 1.875, 2.   ])

In [42]:
# Step 8: create a numpy array of 10 random integers from 20 to 50
# np.random.randint(low, high, size)
# - low = smallest possible number
# - high = biggest possible number (NOT included)
# - size = how many random numbers you want
print("10 random integers between 20 and 50:", np.random.randint(20, 50, 10))


10 random integers between 20 and 50: [42 35 38 21 35 42 43 27 46 49]


In [43]:
# create a numpy array of 10 random integers from 20 to 50
np.random.randint(20, 50, 10)

array([40, 46, 49, 32, 22, 42, 21, 35, 35, 20], dtype=int32)

## 🧠 Key Takeaways — Creating NumPy Arrays

- **NumPy arrays** are like super-fast lists that can handle lots of numbers together.  
- **1-D arrays** are like a single row; **2-D arrays** are like tables (rows × columns).  
- **Ways to make them:**  
  - From a Python list → `np.array([1,2,3])`  
  - With a range → `np.arange(0, 10, 2)`  
  - With all zeros or ones → `np.zeros((2,3))`, `np.ones((2,3))`  
  - Evenly spaced → `np.linspace(1, 2, 5)`  
  - Random numbers → `np.random.randint(10, 50, 5)`  
- `np.arange()` stops **before** the end number;  
  `np.linspace()` includes **both ends**.  
- All elements inside a NumPy array have the **same type** (usually numbers).  


## 🎲 Example — Creating and Understanding a 3D NumPy Array


In [53]:
import numpy as np

# 👇 Create a 3D NumPy array
# Think of this as: 2 "pages" (or layers),
# each page has 3 rows, and each row has 4 columns.

array3d = np.array([
    [   # Page 1
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ],
    [   # Page 2
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ]
])

print("3D array:\n", array3d)
print("\nShape of array:", array3d.shape)


3D array:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

Shape of array: (2, 3, 4)


### 🧠 How to Read the Shape `(2, 3, 4)`

| Dimension | Meaning | Example |
|:--|:--|:--|
| 1st | Number of "pages" (or layers) | 2 pages total |
| 2nd | Number of rows per page | 3 rows per page |
| 3rd | Number of columns per row | 4 columns per row |

📚 You can imagine it like a small book:
- The book has **2 pages** → `(2, …, …)`  
- Each page has **3 lines** → `(2, 3, …)`  
- Each line has **4 words** → `(2, 3, 4)`

So visually:

```
Page 1 ---> [[1,  2,  3,  4],
             [5,  6,  7,  8],
             [9, 10, 11, 12]]

Page 2 ---> [[13, 14, 15, 16],
             [17, 18, 19, 20],
             [21, 22, 23, 24]]
```

👉 Shape `(2, 3, 4)` means:
> 2 pages × 3 rows × 4 columns

---

🧩 You can also use NumPy’s functions to create 3D arrays quickly:
```python
np.zeros((2, 3, 4))   # a 3D array of zeros
np.ones((2, 3, 4))    # a 3D array of ones
np.random.randint(1, 10, (2, 3, 4))  # random integers
```

## 🧠 Key Takeaways — Visualizing Array Shapes — 1D → 2D → 3D


Here’s how NumPy arrays grow in *shape* and *dimension*:

---

### ➕ 1D Array (Shape = `(5,)`)
A simple **line of numbers** — like a train of cars 🚂  
Each value is in one straight row.

```
[1, 2, 3, 4, 5]
```
🧩 Shape: `(5,)` → 1 dimension, 5 elements

---

### 🧱 2D Array (Shape = `(3, 4)`)
Now we have **rows and columns** — like a spreadsheet or a small grid 📊

```
[
 [1,  2,  3,  4],
 [5,  6,  7,  8],
 [9, 10, 11, 12]
]
```
🧩 Shape: `(3, 4)` → 3 rows × 4 columns

---

### 🧊 3D Array (Shape = `(2, 3, 4)`)
Now imagine **stacking 2 grids** (pages) on top of each other — like a small cube or book 📚

```
[
  [ [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9, 10, 11, 12] ],

  [ [13, 14, 15, 16],
    [17, 18, 19, 20],
    [21, 22, 23, 24] ]
]
```
🧩 Shape: `(2, 3, 4)` → 2 pages × 3 rows × 4 columns

---

✨ **Summary:**
| Dimension | Example Shape | Mental Image | Analogy |
|:--|:--|:--|:--|
| 1D | `(5,)` | Line | A row of lockers |
| 2D | `(3, 4)` | Grid | A spreadsheet |
| 3D | `(2, 3, 4)` | Cube | A stack of spreadsheets |

---

💡 **Remember:**  
Each comma inside the shape `(a, b, c)` adds one more dimension — one more “level of structure.”
