---

## 🧩 Selecting Items & Groups from NumPy Arrays

When you work with **NumPy arrays**, you’ll often need to pull out only the parts you care about — like “just the first 3 numbers” or “everything greater than 10.”

NumPy uses **square brackets `[ ]`** for this, just like normal Python lists —  
but it also supports **rows, columns, and logical conditions** for multidimensional arrays.

---

### 🧠 Think of arrays like grids

| Array Type | Shape Example | You Can Select... |
|-------------|---------------|-------------------|
| **1D (line)** | `[0 1 2 3 4]` → shape `(5,)` | Individual numbers or slices of them |
| **2D (table)** | `[[1 2 3], [4 5 6], [7 8 9]]` → shape `(3,3)` | Rows, columns, or both |
| **3D (stack)** | Think “tables stacked on top of each other” | Layers, rows, and columns |

---

### 🪄 Basic patterns you’ll use

```python
# Select a single item
array[2]         # the item at index 2

# Select a slice of items
array[1:4]       # from index 1 up to (but not including) 4

# Select everything from a point onward
array[3:]        # from index 3 to the end

# Select everything before a point
array[:3]        # from start to index 3 (exclusive)
```

---

### 🎯 When arrays have rows and columns

```python
array2D[1, 2]    # Row 1, Column 2 (single pair)
array2D[0:2, 0:2] # First 2 rows × first 2 columns
```

- The **first number** = row position  
- The **second number** = column position  
- Use commas to separate them → like coordinates on a grid 📊

---

### 🔍 Conditional selections (power move!)

You can grab numbers that meet a condition:

```python
array[array > 10]              # all numbers greater than 10
array[(array > 5) & (array < 15)]  # between 5 and 15
```

NumPy checks each element and returns only the ones that match the rule.  
This is called **Boolean masking** — because you’re using True/False masks to “filter” the array.

---

### 🧩 Visualization

```
Original array: [ 0,  1,  2,  3,  4]
Indexes:        [ 0,  1,  2,  3,  4]
array[1:4] → [1, 2, 3]
```

---

### 💡 Key takeaway:
> Use brackets `[ ]` to “zoom in” on the exact data you need — by **position**, **range**, or **condition**.

---



## 🧭 Overview — Selecting Items & Groups from NumPy Arrays

Goal: Practice **indexing**, **slicing**, and **conditional selection** in NumPy.

You will:
- Select single items and ranges from **1D arrays**.
- Select rows, columns, and sub-matrices from **2D arrays**.
- Use **Boolean masks** to filter values by conditions.
- Combine conditions with **logical AND (`&`)** and **OR (`|`)**.


In [1]:
# ============================================
# Step 0 — Imports and reproducibility
# ============================================
import numpy as np
np.random.seed(42)  # 🌱 same "random" results every run


In [2]:
# ============================================
# Step 1 — Indexing & slicing in 1D arrays
# ============================================

# Create a simple 1D array: [0, 1, 2, 3, 4]
a1 = np.arange(5)
print("a1:", a1, "| shape:", a1.shape)  # (5,)

# --- Single item (by position)
print("\nSingle item at index 1:", a1[1])     # -> 1

# --- Slice: start:stop  (stop is EXCLUDED)
print("Slice a1[1:4]  ->", a1[1:4])          # -> [1 2 3]
print("Slice a1[:4]   ->", a1[:4])           # -> [0 1 2 3] (from start)
print("Slice a1[3:]   ->", a1[3:])           # -> [3 4]     (to the end)
print("Slice a1[:]    ->", a1[:])            # -> full copy


a1: [0 1 2 3 4] | shape: (5,)

Single item at index 1: 1
Slice a1[1:4]  -> [1 2 3]
Slice a1[:4]   -> [0 1 2 3]
Slice a1[3:]   -> [3 4]
Slice a1[:]    -> [0 1 2 3 4]


In [5]:
# initialize array0 
# as a one-dimensional numpy array containing integers 0 to 4, including 0 and 4
array0 = np.arange(5)
print(array0)
print(array0.shape)

[0 1 2 3 4]
(5,)


In [9]:
# select the item at index 1 from array0
array0[1]
print(array0[1])


1


In [12]:
# select the items at indices 1 to 3 inclusive from array0
array0 = np.arange(5)
print(array0)
array0[1:4]  # items 1 to 3 selected

[0 1 2 3 4]


array([1, 2, 3])

In [14]:
# select the items at indices 0 to 3 inclusive from array0
array0 = np.arange(5)
print(array0)
array0[0:4]  # items 0 to 3 selected

[0 1 2 3 4]


array([0, 1, 2, 3])

In [19]:
# select the items starting at index 3 until the end of array0
array0 = np.arange(5)
print(array0)
array0[3:]  # items starting at 3 to the end of array

[0 1 2 3 4]


array([3, 4])

In [58]:
# ============================================
# Step 2 — Indexing & slicing in 2D arrays (rows × cols)
# ============================================

# Make a 3×3 matrix
array_2 = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])
print("array_2:\n", array_2, "\nshape:", array_2.shape)     # (3, 3), 2D three rows x 3 columns = 9 elements

# --- Select a single item (row, col)
# Two equivalent styles:
print("\nItem at row 0, col 0 (double bracket):", array_2[0][0])   # row [0], column [0] = 1
print("Item at row 1, col 2 (single bracket):",  array_2[1, 2])    # row 1 column 2 = [1, 2] = 6

# --- Select an entire row / column
print("\nRow 0:", array_2[0, :])       # row [0, :] to the end of the row = [1 2 3]
print("Col 1:", array_2[:, 1])        # column [:, 1] = [2 5 8]

# --- Sub-matrix (rows 0..1, cols 0..1)
print("\nTop-left 2×2 block:\n", array_2[0:2, 0:2])  # rows 0 and 1; cols 0 and 1
#  [[1 2]
# [4 5]]

# --- First two items from EACH row
print("\nFirst two columns of all rows:\n", array_2[:, :2])
# First two columns of all rows:
# [[1 2]
# [4 5]
# [7 8]]

# --- First two items from rows BEFORE row 2 (i.e., rows 0 and 1)
print("\nRows 0..1, first two cols:\n", array_2[:2, :2])
#  [[1 2]
# [4 5]]

# --- Everything before row 2 (rows 0 and 1), all columns
print("\nRows 0..1, all cols:\n", array_2[:2, :])
#  [[1 2 3]
# [4 5 6]]

array_2:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
shape: (3, 3)

Item at row 0, col 0 (double bracket): 1
Item at row 1, col 2 (single bracket): 6

Row 0: [1 2 3]
Col 1: [2 5 8]

Top-left 2×2 block:
 [[1 2]
 [4 5]]

First two columns of all rows:
 [[1 2]
 [4 5]
 [7 8]]

Rows 0..1, first two cols:
 [[1 2]
 [4 5]]

Rows 0..1, all cols:
 [[1 2 3]
 [4 5 6]]


In [24]:
# initialize array1 as a three-dimensional numpy array
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array1)

# select the item in row 0 column 0 from array1 using double bracket notation
array1[0][0]
print("\narray1[0][0]:", array1[0][0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

array1[0][0]: 1


In [40]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array1)

# select the item in row 0 column 0 from array1 using single bracket notation
array1[0, 0]
print("\narray1[0, 0]:", array1[0, 0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

array1[0, 0]: 1


In [38]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array1)

# select the item in row 1 column 2 from array1 using double bracket notation
array1[1][2]
print("\narray1[1][2]:", array1[1][2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

array1[1][2]: 6


In [41]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array1)

# select the item in row 1 column 2 from array1 using single bracket notation
array1[1, 2]
print("\narray1[1, 2]:", array1[1, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

array1[1, 2]: 6


In [42]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array1)

# select first two items from row 0 of array1
array1[:1, :2]
print("\narray1[:1, :2]:", array1[:1, :2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

array1[:1, :2]: [[1 2]]


In [43]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array1)

# select first two items from every row until row 1 inclusive from array1
array1[:2, :2]
print("\narray1[:2, :2]:", array1[:2, :2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

array1[:2, :2]: [[1 2]
 [4 5]]


In [45]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array1)

# select first two items from each row of array1
array1[:, :2]
print("\narray1[:, :2]:", array1[:, :2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

array1[:, :2]: [[1 2]
 [4 5]
 [7 8]]


In [49]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array1)

# select row 0 from array1
array1[0,]
print("\narray1[0,]:", array1[0,])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

array1[0,]: [1 2 3]


In [50]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array1)

# select everything before row 2 from array1
array1[:2]
print("\narray1[:2]:", array1[:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

array1[:2]: [[1 2 3]
 [4 5 6]]


In [59]:
# ============================================
# Step 2 — Indexing & slicing in 2D arrays (rows × cols)
# ============================================

# Make a 3×3 matrix
array_2 = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])
print("array_2:\n", array_2, "\nshape:", array_2.shape)     # (3, 3), 2D three rows x 3 columns = 9 elements

# --- Select a single item (row, col)
# Two equivalent styles:
print("\nItem at row 0, col 0 (double bracket):", array_2[0][0])   # row [0], column [0] = 1
print("Item at row 1, col 2 (single bracket):",  array_2[1, 2])    # row 1 column 2 = [1, 2] = 6

# --- Select an entire row / column
print("\nRow 0:", array_2[0, :])       # row [0, :] to the end of the row = [1 2 3]
print("Col 1:", array_2[:, 1])         # column [:, 1] = [2 5 8]

# --- Sub-matrix (rows 0..1, cols 0..1)
print("\nTop-left 2×2 block:\n", array_2[0:2, 0:2])
# rows 0 and 1; cols 0 and 1

# --- First two items from EACH row
print("\nFirst two columns of all rows:\n", array_2[:, :2])

# --- First two items from rows BEFORE row 2 (i.e., rows 0 and 1)
print("\nRows 0..1, first two cols:\n", array_2[:2, :2])

# --- Everything before row 2 (rows 0 and 1), all columns
print("\nRows 0..1, all cols:\n", array_2[:2, :])


array_2:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
shape: (3, 3)

Item at row 0, col 0 (double bracket): 1
Item at row 1, col 2 (single bracket): 6

Row 0: [1 2 3]
Col 1: [2 5 8]

Top-left 2×2 block:
 [[1 2]
 [4 5]]

First two columns of all rows:
 [[1 2]
 [4 5]
 [7 8]]

Rows 0..1, first two cols:
 [[1 2]
 [4 5]]

Rows 0..1, all cols:
 [[1 2 3]
 [4 5 6]]


In [60]:
# initialize array2 
# as a one-dimensional numpy array containing all even integers between 0 and 20 inclusive
array2 = np.arange(0, 21, 2)
array2
print(array2)

[ 0  2  4  6  8 10 12 14 16 18 20]


In [65]:
# select the items from array2 that are greater than or equal to 12
array2[array2 >= 12]

array([12, 14, 16, 18, 20])

In [66]:
# select the items from array2 that are greater than 7 and less than 13
array2[(array2 > 7) & (array2 < 13)]

array([ 8, 10, 12])

In [69]:
# ============================================
# Step 3 — Conditional selection (Boolean masking) in 1D
# ============================================

# Even numbers from 0 to 20 (inclusive of 20)
array_3 = np.arange(0, 21, 2)
print("array_3:", array_3)

# --- Keep values ≥ 12
mask_ge12 = array_3 >= 12                 # Boolean mask (True/False per element)
print("\nMask array_3>=12:", mask_ge12)
print("array_3[array_3>=12]  ->", array_3[mask_ge12])

# --- Combine conditions: (a3 > 7) & (a3 < 13)
# IMPORTANT: use parentheses around each condition with & and |
between_7_13 = array_3[(array_3 > 7) & (array_3 < 13)]
print("\nBetween 7 and 13 (exclusive):", between_7_13)

# --- OR example: values < 4 OR > 16
outside_range = array_3[(array_3 < 4) | (array_3 > 16)]
print("Less than 4 OR greater than 16:", outside_range)


array_3: [ 0  2  4  6  8 10 12 14 16 18 20]

Mask array_3>=12: [False False False False False False  True  True  True  True  True]
array_3[array_3>=12]  -> [12 14 16 18 20]

Between 7 and 13 (exclusive): [ 8 10 12]
Less than 4 OR greater than 16: [ 0  2 18 20]


In [70]:
# ============================================
# Step 4 — Conditional selection in 2D (row/col filtering)
# ============================================

b = np.random.randint(1, 21, (4, 5))  # 4 rows × 5 cols, values 1..20
print("b (4×5):\n", b)

# --- Keep only values > 10 (same shape; others dropped in a flat result)
print("\nValues > 10:", b[b > 10])    # 1D view of matches

# --- Example: keep rows where the row's mean is ≥ 10
row_means = b.mean(axis=1)            # mean per row
rows_keep_mask = row_means >= 10
print("\nRow means:", row_means)
print("Rows with mean ≥ 10:\n", b[rows_keep_mask, :])

# --- Example: keep columns where the column's max is ≥ 15
col_max = b.max(axis=0)               # max per column
cols_keep_mask = col_max >= 15
print("\nCol max:", col_max)
print("Columns with max ≥ 15:\n", b[:, cols_keep_mask])


b (4×5):
 [[ 7 20 15 11  8]
 [ 7 19 11 11  4]
 [ 8  3  2 12  6]
 [ 2  1 12 12 17]]

Values > 10: [20 15 11 19 11 11 12 12 12 17]

Row means: [12.2 10.4  6.2  8.8]
Rows with mean ≥ 10:
 [[ 7 20 15 11  8]
 [ 7 19 11 11  4]]

Col max: [ 8 20 15 12 17]
Columns with max ≥ 15:
 [[20 15  8]
 [19 11  4]
 [ 3  2  6]
 [ 1 12 17]]
