In [4]:
# import relevant libraries
import numpy as np

In [18]:
# create a numpy array of 20 random integers from 1 to 50 & save in a variable
# np.random.randint(low, high, size)
# - low = smallest possible number
# - high = biggest possible number (NOT included)
# - size = how many random numbers you want
array_random = np.random.randint(1, 50, 20)
array_random


array([30, 31, 42, 40, 32, 26,  2, 35, 42, 35, 18, 33, 29, 33,  5, 38,  8,
       46, 35, 14], dtype=int32)

In [10]:
# find minimum value in array_random
array_random.min()

np.int32(1)

In [11]:
# find maximum value in array_random
array_random.max()

np.int32(49)

In [20]:
# find minimum and maximum values and print them clearly
min_value = int(array_random.min())   # convert np.int32 → regular int
max_value = int(array_random.max())

print("Random Array:\n", array_random)
print(f"\nMinimum Value: {min_value}")
print(f"Maximum Value: {max_value}")


Random Array:
 [30 31 42 40 32 26  2 35 42 35 18 33 29 33  5 38  8 46 35 14]

Minimum Value: 2
Maximum Value: 46


## 🧠 Key Takeaways — NumPy `.min()` and `.max()`

- **`.min()`** and **`.max()`** are built-in NumPy array methods that work directly on the array (no need to call `np.min()` unless you prefer the function form).  
- Both methods scan all array elements and return a **single scalar** value (the min or max).  
- You can also specify an **axis** for multi-dimensional arrays:  
  - `array.min(axis=0)` → min of each column  
  - `array.min(axis=1)` → min of each row  
- Using `np.random.seed()` makes your random arrays reproducible — essential for consistent study results.  
- In data analysis, these methods are useful for **identifying outliers**, **checking data ranges**, and **verifying normalization**.

🧩 **Example Use Case:**  
> You might use `.min()` and `.max()` to check whether all student grades fall between 0 and 100 before running statistical analysis.


In [21]:
# ============================================
# 💻 Example: Finding Minimum and Maximum in a NumPy Array
# ============================================

import numpy as np

# Step 1 – Set a random seed for reproducibility
# This ensures the same random numbers appear every time you run the cell.
np.random.seed(42)

# Step 2 – Create a 1D NumPy array with 20 random integers between 1 and 50
array_random = np.random.randint(1, 51, 20)
print("🎲 Random Array:\n", array_random)

# Step 3 – Find the minimum value in the array
# .min() scans the entire array and returns the smallest number
min_value = array_random.min()
print("\n🔹 Minimum Value:", min_value)

# Step 4 – Find the maximum value in the array
# .max() scans the entire array and returns the largest number
max_value = array_random.max()
print("🔸 Maximum Value:", max_value)

# Step 5 – Summary message combining both results
print(f"\n✅ The minimum is {min_value}, and the maximum is {max_value}.")


🎲 Random Array:
 [39 29 15 43  8 21 39 19 23 11 11 24 36 40 24  3 22  2 24 44]

🔹 Minimum Value: 2
🔸 Maximum Value: 44

✅ The minimum is 2, and the maximum is 44.


## 🌱 Understanding `np.random.seed()`

### 🎲 What It Does
`np.random.seed()` is used to make random number generation **reproducible** — meaning you get **the same random results every time** you run the code.

Think of it like planting a seed in a garden 🌱:
- If you plant **the same seed**, you’ll grow **the same garden** every time.
- If you plant **a different seed**, you’ll grow a **different garden**.

---

### 💻 Example
```python
import numpy as np

np.random.seed(42)             # 🌱 plant the random seed
array_random = np.random.randint(1, 50, 10)
print(array_random)
```

**Output (every run):**
```
[39 15 43  9 24 22 30  5 11 19]
```

If you change the seed (e.g., `np.random.seed(10)`),  
the numbers will be different — but **still repeatable** each time you use that seed.

---

### 🧩 Why It’s Useful
| Scenario | Why `.seed()` Helps |
|-----------|--------------------|
| 🧠 Learning | Ensures your instructor or classmates see the same random results |
| 🧰 Debugging | Makes testing predictable and repeatable |
| 📊 Data Science | Keeps analysis results consistent when randomness is used |
| 🧾 Reproducible Research | Ensures identical outputs in future runs or publications |

---

### ✅ In Short
- `np.random.seed(42)` → same random numbers every run  
- `np.random.seed(7)` → different numbers, but repeatable with that seed  
- No seed → new random numbers every time

**Controlled randomness = predictable experiments.**

---
