## 📐 Overview — Understanding Shapes and Reshaping NumPy Arrays

A **shape** describes the structure of a NumPy array — how many rows, columns, or layers it has.

- The **`.shape` attribute** tells you the size of each dimension.  
- The **`.reshape()` method** creates a *new array* with the same data, arranged into a different shape.

These tools help you understand and reorganize data when preparing it for analysis or machine learning.


In [9]:
# ============================================
# 🧮 Step 1 – Import NumPy and set a random seed
# ============================================
import numpy as np

np.random.seed(42)  # 🌱 ensures reproducibility


In [4]:
array0 = np.array([])
print(array0)

[]


In [14]:
# find the shape of array0
array0.shape  # 1D container, 0 items

(0,)

In [6]:
array1 = np.array([1, 2, 3, 4, 5])
print(array1)

[1 2 3 4 5]


In [15]:
# find the shape of array1
array1.shape  # 1D array with 5 elements

(5,)

In [18]:
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [22]:
array2 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
array2.shape
# Output: (3, 3)


(3, 3)

In [21]:
# find the shape of array2
array2.shape  # 2D array with 3 rows x 3 columns = 9 elements

(3, 3)

---

## ✅ In Short — Understanding Array Shapes in NumPy

| Shape Format | Dimensionality | Description | Example |
|---------------|----------------|--------------|----------|
| `(n,)` | **1D** | 1D array (vector) with *n* elements | `[1, 2, 3, 4, 5] → (5,)` |
| `(r, c)` | **2D** | 2D array (matrix) with *r* rows × *c* columns | `[[1,2,3],[4,5,6]] → (2, 3)` |
| `(r, c, d)` | **3D** | 3D array (tensor) with *r × c × d* total elements — used for images, videos, and higher-dimensional data | Shape example: `(2, 3, 4)` |

---

### 🧠 Quick Visualization

```
1D → [1, 2, 3, 4, 5]          Shape → (5,)

2D → [[1, 2, 3],
       [4, 5, 6]]             Shape → (2, 3)

3D → [[[1,2,3], [4,5,6]],
       [[7,8,9], [10,11,12]]] Shape → (2, 2, 3)
```

---

✨ **Summary:**  
- `(n,)` → **1D** with *n* elements  
- `(r, c)` → **2D** with *r* rows and *c* columns  
- `(r, c, d)` → **3D** with *r × c × d* items *(used for color images, tensors, etc.)*

---


---

## 🎨 Visualizing Array Dimensions

### 🟦 **1D Array (Vector)**
A simple list of numbers — **one line of data**
```
[1, 2, 3, 4, 5]
Shape → (5,)
```
📏 One dimension → length only (no rows or depth)

---

### 🧩 **2D Array (Matrix)**
Numbers arranged in **rows × columns**
```
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]
Shape → (3, 3)
```
🧱 Two dimensions → height (rows) × width (columns)

---

### 📦 **3D Array (Tensor)**
A **stack** of 2D arrays — imagine several “layers” or “sheets” of data  
*(used in images, videos, and deep learning)*
```
[
  [[1, 2, 3],
   [4, 5, 6]],

  [[7, 8, 9],
   [10, 11, 12]]
]
Shape → (2, 2, 3)

Shape → (layers, rows, columns)
          ↑        ↑       ↑
          2        2       3
```
🧊 Three dimensions → depth (layers) × height (rows) × width (columns) = 12 elements total

---

### 🌈 **Analogy Summary**

| Dimension | Visual | Example Shape | Think Of |
|------------|---------|----------------|-----------|
| 1D | ➖ Line | `(5,)` | A list of numbers |
| 2D | 🧱 Grid | `(3, 3)` | A table or spreadsheet |
| 3D | 📦 Cube | `(2, 2, 3)` | A stack of spreadsheets (like layers in Excel) |

---

✨ **Tip:**  
In higher dimensions (4D, 5D…), each new axis represents another “layer of grouping,” e.g., batches of 3D data used in machine learning.

---


In [25]:
array_zeros = np.zeros((4, 5))
print(array_zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [26]:
# find the shape of array_zeros
array_zeros.shape  # 2D, 4 rows, 5 columns

(4, 5)

In [27]:
array_ones = np.ones((3, 6))
print(array_ones)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [28]:
# find the shape of array_ones
array_ones.shape  # 2D, 3 rows, 6 columns

(3, 6)

In [32]:
# ============================================
# 🔄 Step 3 – Reshape a 1D array into 2D forms
# ============================================

# Create a 1D array of 25 random integers
array_r0 = np.random.randint(1, 51, 25)
print("array_r0:\n", array_r0)
print("Shape before reshape:", array_r0.shape)  # (25,) 1D array with 25 elements

# Reshape into 5 rows × 5 columns
array_r0_reshaped = array_r0.reshape((5, 5))
print("\narray_r0 reshaped (5x5):\n", array_r0_reshaped)
print("Shape after reshape:", array_r0_reshaped.shape)  # 2D, 5 rows, 5 columns


array_r0:
 [36 14 31 48 15  8 14 23 40 21 16 45 18 47 24 26 25 45 41 29 15 45  1 25
  7]
Shape before reshape: (25,)

array_r0 reshaped (5x5):
 [[36 14 31 48 15]
 [ 8 14 23 40 21]
 [16 45 18 47 24]
 [26 25 45 41 29]
 [15 45  1 25  7]]
Shape after reshape: (5, 5)


In [34]:
array_r0 = np.random.randint(1, 51, 25)
print(array_r0)

[24 37 35 44 40 22 27 35  1 35 37 47 14  3  1  5 26 14 39 27  9 15 15 26
 42]


In [36]:
# find the shape of array_r0
array_r0.shape  # 1D array with 25 elements

(25,)

In [44]:
# reshape array_r0 
# to create a new multi-dimensional numpy array 
# containing array_r0's items with 5 rows & 5 columns
array_r0_reshaped = array_r0.reshape((5, 5))
print(array_r0_reshaped)  # 2D, 5 rows x 5 columns = 25 elements

[[24 37 35 44 40]
 [22 27 35  1 35]
 [37 47 14  3  1]
 [ 5 26 14 39 27]
 [ 9 15 15 26 42]]


In [45]:
# note that array_r0 itself was not modified
array_r0

array([24, 37, 35, 44, 40, 22, 27, 35,  1, 35, 37, 47, 14,  3,  1,  5, 26,
       14, 39, 27,  9, 15, 15, 26, 42], dtype=int32)

In [47]:
array_r1 = np.random.randint(1, 50, 20)
print(array_r1)

[ 2 42 45  6 28 28 44 44 20 30 11 28 25 39 33  1 27 13 41  3]


In [49]:
# find the shape of array_r1
array_r1.shape  # 1D with 20 elements

(20,)

In [51]:
# reshape array_r1
# to create a new multi-dimensional numpy array containing array_r1's items 
# with 10 rows & 2 columns
array_1_reshaped = array_r1.reshape((10, 2))
print(array_1_reshaped)  # 2D, 10 rows x 2 columns = 20 elements

[[ 2 42]
 [45  6]
 [28 28]
 [44 44]
 [20 30]
 [11 28]
 [25 39]
 [33  1]
 [27 13]
 [41  3]]


In [52]:
# reshape array_r1
# to create a new multi-dimensional numpy array containing array_r1's items 
# with 2 rows & 10 columns
array_r1.reshape((2, 10))

array([[ 2, 42, 45,  6, 28, 28, 44, 44, 20, 30],
       [11, 28, 25, 39, 33,  1, 27, 13, 41,  3]], dtype=int32)

In [53]:
# reshape array_r1
# to create a new multi-dimensional numpy array containing array_r1's items 
# with 4 rows & 5 columns
array_r1.reshape((4, 5))

array([[ 2, 42, 45,  6, 28],
       [28, 44, 44, 20, 30],
       [11, 28, 25, 39, 33],
       [ 1, 27, 13, 41,  3]], dtype=int32)

In [54]:
# reshape array_r1
# to create a new multi-dimensional numpy array containing array_r1's items 
# with 5 rows & 4 columns
array_r1.reshape((5, 4))

array([[ 2, 42, 45,  6],
       [28, 28, 44, 44],
       [20, 30, 11, 28],
       [25, 39, 33,  1],
       [27, 13, 41,  3]], dtype=int32)

In [55]:
# note that array_r1 itself was not modified
array_r1

array([ 2, 42, 45,  6, 28, 28, 44, 44, 20, 30, 11, 28, 25, 39, 33,  1, 27,
       13, 41,  3], dtype=int32)

In [60]:
# ============================================
# 🔢 Step 6 – Flattening a 2D array into 1D
# ============================================

# make a 2D (two-dimensional) array that has 4 rows and 4 columns
# think of it like a small 4x4 table full of random numbers
array_r2 = np.random.randint(1, 51, (4, 4))
print("array_r2 (4x4):\n", array_r2)

# .shape tells us what the array looks like right now
# (4, 4) means it has 4 rows and 4 columns
print("Shape before flattening:", array_r2.shape)  # 2D, 4 rows x 4 columns = 16 elements 

# flatten means “squish everything into one long line”
# reshape(16) tells NumPy to make 1 line with 16 numbers
# (because 4 x 4 = 16 total numbers)
array_flat = array_r2.reshape(16)

# show what the flattened array looks like
print("\nFlattened array (1D):\n", array_flat)

# now .shape shows (16,) which means one long line with 16 numbers
print("Shape after flattening:", array_flat.shape)  # 1D row with 16 elements



array_r2 (4x4):
 [[19 20 32  7]
 [41 33 40 39]
 [18 40  1 11]
 [28 25 50 23]]
Shape before flattening: (4, 4)

Flattened array (1D):
 [19 20 32  7 41 33 40 39 18 40  1 11 28 25 50 23]
Shape after flattening: (16,)


In [62]:
array_r2 = np.random.randint(1, 50, (4, 4))
print(array_r2)  # 2D, 4 rows x 4 columns = 16 elements

[[31 30 42 35]
 [ 7 16 26 48]
 [49  2  1 48]
 [12  5 37 32]]


In [63]:
# find the shape of array_r2
array_r2.shape

(4, 4)

In [67]:
# reshape array_r2 
# to create a new one-dimensional numpy array containing array_r2's items 
# with length 16
array_r2_1d = array_r2.reshape(16)
print(array_r2_1d)

[31 30 42 35  7 16 26 48 49  2  1 48 12  5 37 32]


In [66]:
# note that array_r2 itself was not modified
print(array_r2)

[[31 30 42 35]
 [ 7 16 26 48]
 [49  2  1 48]
 [12  5 37 32]]


## 🧠 Key Takeaways — `.shape` and `.reshape()`

| Operation | Purpose | Example Output |
|------------|----------|----------------|
| `.shape` | Returns the size of each dimension | `(3, 4)` |
| `.reshape(a, b)` | Rearranges data into *a × b* matrix | `(5, 5)` |
| `.reshape(n)` | Flattens into 1D with *n* elements | `(16,)` |

- **`.shape`** tells you the current layout of an array.  
- **`.reshape()`** creates a *new* array with a different layout — it does *not* modify the original.  
- The **total number of elements** must stay the same before and after reshaping.  
  - Example: `5 × 5 = 25` elements → can’t reshape to `(4, 5)` (only 20 elements).  
- Use `.reshape(-1)` to let NumPy automatically figure out one dimension.

---

### 🧩 Visual Summary

```
Before reshape (1D): [1, 2, 3, 4, 5, 6]
After reshape (2x3):
[[1, 2, 3],
 [4, 5, 6]]
```

✨ **In one line:**  
> `.shape` tells you the structure — `.reshape()` lets you reorganize it.


---

## 🧱 How Brackets Define Dimensions in NumPy

Each level of square brackets `[]` adds a new **dimension** to an array.

| Bracket Level | Example | Array Type | Shape | Description |
|----------------|----------|-------------|--------|--------------|
| `[ ]` | `[1, 2, 3, 4]` | **1D Array** | `(4,)` | A single line of data — one dimension only |
| `[ [ ] ]` | `[[1, 2, 3], [4, 5, 6]]` | **2D Array** | `(2, 3)` | Two lists stacked vertically — rows × columns |
| `[ [ [ ] ] ]` | `[[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]]` | **3D Array** | `(2, 2, 3)` | A stack of 2D grids — layers × rows × columns |

---

### 🧩 Visualization

```
1D → [1, 2, 3, 4]
     Shape → (4,)

2D → [[1, 2, 3],
      [4, 5, 6]]
     Shape → (2, 3)

3D → [[[1, 2, 3],
       [4, 5, 6]],
      [[7, 8, 9],
       [10, 11, 12]]]
     Shape → (2, 2, 3)
```

---

### 🧠 Key Idea
> Each extra level of brackets `[ ]` adds **one more dimension** to your data:
> - 1D → a **line**
> - 2D → a **grid**
> - 3D → a **cube**

---

✨ **In short:**  
> Brackets define the “depth” of your data structure — more brackets = higher dimensionality.

---
